################################################################################
# Generic .travis.yml file for running continuous integration on Travis-CI for
# any ROS package.
# 
# Parts of this CI build follow the example under:
#   - http://felixduvallet.github.io/ros-travis-integration
#   - https://github.com/felixduvallet/ros-travis-integration
#
# The script prepares everything for running the docker CI builder. The CI
# builder installs all dependencies, compiles the code and runs all the tests.
################################################################################
dist: trusty
sudo: required
language:
  - generic
services:
  - docker

before_install:
  - docker pull labust/docker-ci:indigo

script:
  - export REPONAME=`basename \`pwd\``
  - docker run -e "REPONAME=$REPONAME" -v `pwd`:/root/catkin_ws/src/$REPONAME:r labust/docker-ci:indigo "~/ros_ci_test.sh"
