#Manual controllers
nu_manual/maximum_speeds: [1,1,1,0,0,0.5]
ref_manual/maximum_speeds: [1,1,1,0,0,0.5]
#DP controller
dp_controller/closed_loop_freq: [0.2,0.2]
#Alt/Depth controller
alt_controller/closed_loop_freq: 0.3
#Heading controller
hdg_controller/closed_loop_freq: 0.5
#Velocity controller
velocity_controller/closed_loop_freq: [0.8,0.8,1.2,1.0,1.0,1.8]
velocity_controller/auto_tracking: [0.0,0.0,0.0,1.0,1.0,0.0]
velocity_controller/output_limits: [100.0,100.0,100.0,0.0,0.0,100.0]
velocity_controller/Ts: 0.1
velocity_controller/timeout: 2.0
velocity_controller/external_ident: true
