#Manual controllers
nu_manual/maximum_speeds: [0.4,0.4,0.1,0,0,0.3]
ref_manual/maximum_speeds: [0.5,0.5,0.5,0,0,0.5]
#DP controller
dp_controller/closed_loop_freq: [0.15,0.1]
dp_controller/use_ip: true
#Alt/Depth controller
alt_controller/closed_loop_freq: 0.3
#Heading controller
hdg_controller/closed_loop_freq: 0.3
#hdg_controller/use_ip: false - don't use this before trying in simulation
hdg_controller/Ts: 0.2
hdg_controller/max_n: 60
