#Manual controllers
nu_manual/maximum_speeds: [0.4,0.4,0.1,0,0,0.3]
ref_manual/maximum_speeds: [0.5,0.5,0.5,0,0,0.5]
ref_manual/feedforward_speeds: false
joystick_mapping/scale_map: [1.0, -1.0 ,1.0,0.0,0.0,-1.0]
#DP controller
dp_controller/closed_loop_freq: [0.15,0.1]
dp_controller/use_ip: false
dp_controller/Ts: 0.1
#Altitude controller
alt_controller/closed_loop_freq: 0.1
alt_controller/use_ip: true
alt_controller/min_altitude: 0.5
#Depth controller
depth_controller/closed_loop_freq: 0.1
depth_controller/use_ip: true
depth_controller/min_altitude: 0.5
#Heading controller
hdg_controller/closed_loop_freq: 0.15
hdg_controller/use_ip: false
hdg_controller/Ts: 0.1
#Velocity controller
velocity_controller/closed_loop_freq: [0.25,0.2,0.1,1.0,1.0,0.5]
velocity_controller/auto_tracking: [1.0,1.0,1.0,1.0,1.0,1.0]
velocity_controller/output_limits: [64,64,64,0.0,0.0,25]
velocity_controller/Ts: 0.1
velocity_controller/timeout: 2.0
velocity_controller/external_ident: true
