#Manual controllers
nu_manual/maximum_speeds: [0.4,0.4,0.1,0,0,0.3]
ref_manual/maximum_speeds: [0.5,0.5,0.5,0,0,0.5]
#DP controller
dp_controller/closed_loop_freq: [0.15,0.1]
dp_controller/use_ip: false
dp_controller/Ts: 0.1
#Alt/Depth controller
alt_controller/closed_loop_freq: 0.15
alt_controller/use_ip: true
#Heading controller
hdg_controller/closed_loop_freq: 0.15
hdg_controller/use_ip: false
hdg_controller/Ts: 0.1
#Velocity controller
velocity_controller/closed_loop_freq: [0.25,0.2,0.15,1.0,1.0,0.4]
velocity_controller/auto_tracking: [1.0,1.0,1.0,1.0,1.0,1.0]
velocity_controller/output_limits: [64,64,160,0.0,0.0,16]
velocity_controller/Ts: 0.1
velocity_controller/timeout: 2.0
velocity_controller/external_ident: true
