#Manual controllers
nu_manual/maximum_speeds: [0.4,0.4,0.1,0,0,0.3]
ref_manual/maximum_speeds: [0.5,0.5,0.5,0,0,0.5]
#DP controller
dp_controller/closed_loop_freq: [0.15,0.1]
dp_controller/use_ip: false
#Alt/Depth controller
alt_controller/closed_loop_freq: 0.1
alt_controller/use_ip: true
#Heading controller
hdg_controller/closed_loop_freq: 0.1
hdg_controller/use_ip: false
hdg_controller/Ts: 0.2
#Velocity controller
velocity_controller/closed_loop_freq: [0.15,0.1,0.1,1.0,1.0,0.3]
velocity_controller/auto_tracking: [1.0,1.0,1.0,1.0,1.0,1.0]
velocity_controller/output_limits: [30,30,180.0,0.0,0.0,90.0]
velocity_controller/Ts: 0.2
velocity_controller/timeout: 2.0
velocity_controller/external_ident: true
