#             Type+LogOrder    Topic names             
log_data: [['navsts_t',       ['stateHat', 'meas', 'stateRef']], 
           ['bodyvelreq_t',   ['nuRefMerged']],
           ['bodyforcereq_t', ['tauOut', 'tauAch']],
           ['twist_stamped_t',['currentsHat','dvl','velo_instrument','velo_earth','watervelo_instrument','watervelo_earth']],
           ['pladypos_info_t',['pladypos_info']],
           ['imu_info_t',     ['imu_info']],
           ['imu_t',          ['imu']]]
           
