#Parameters:	         u     v     w     r     xp    yp   zp   psi    xc   yc    b  buoyancy
ekfnav/Q: [diagonal, [0.001,0.001,0.001,0.01,0.001,0.001,0.001,0.001,0.001, 0.001, 0.01, 0.001]]
#Parameters:	          u  v     w    r   xp yp zp    psi     xc   yc    b   buoyancy
ekfnav/R: [diagonal, [0.01,0.01,0.001,0.001,16,16,0.01,0.001,0.001,0.001,9999,9999]]
ekfnav/V: [diagonal, [1,1,1,1,1,1,1,1,1,1,1,1]]
#Parameters:          u   v   w  r  xp yp zp psi xc yc b buoyancy 
ekfnav/P: [diagonal, [0.1,0.1,0.1,0.1,9,9,0.1,0.1,0,0,1,1]]
ekfnav/x0: [0,0,0,0,0,0,0,0,0,0,0,0]
